import { Geist, Geist_Mono } from 'next/font/google';
import { Nunito } from 'next/font/google';
import './globals.css';

import Footer from './components/Footer';
import Navbar from './components/Navbar';
import { Toaster } from 'react-hot-toast';

// Fonts
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight: ['200', '300', '400', '600', '700', '800'],
  style: ['normal', 'italic'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="flex flex-col min-h-screen font-[var(--font-nunito)] antialiased bg-white text-gray-900">
        {/* Toasts */}
        <Toaster position="top-center" reverseOrder={false} />

        {/* Navbar */}
        <Navbar />

        {/* Main content (takes full remaining height) */}
        <main className="flex-grow">{children}</main>

        {/* Footer (sticks to bottom) */}
        <Footer />
      </body>
    </html>
  );
}
